export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";

export const SET_USER_PRODUCTS = "SET_USER_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const SET_SALES_RECORDS = "SET_SALES_RECORDS";
export const SET_WALLET_BALANCE = "SET_WALLET_BALANCE";